spring:
  application:
    name: SpatialSearch
  datasource:
    url: jdbc:postgresql://localhost:5432/testgis
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
